name: Deploy To Glitch
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v2
      - name: âš¡ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: ğŸ”„ Install dependencies
        run: npm install
      - name: âœ¨ Build project
        run: npm run build
      - name: ğŸ  Deploy To Glitch
        uses: kanadgupta/glitch-sync@main
        with:
          project-id: ${{ secrets.PROJECT_ID }}
          auth-token: ${{ secrets.AUTH_TOKEN }}